# Backend Dockerfile

# Use the official Node.js image as a parent image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on (assuming default port 3000)
EXPOSE 5500

# Start the application
CMD ["npm", "start"]
